//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceModemToolbarSync
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuListItemClass", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceModemToolbarSync")]
    public partial class MenuListItemClass : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CaptionField;
        
        private string HintField;
        
        private System.Drawing.Image ImgField;
        
        private System.Collections.Generic.KeyValuePair<string, System.Collections.Generic.KeyValuePair<string, ModemWebUtility.ModemPostObjects>[]>[] LinksField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption
        {
            get
            {
                return this.CaptionField;
            }
            set
            {
                this.CaptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hint
        {
            get
            {
                return this.HintField;
            }
            set
            {
                this.HintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Image Img
        {
            get
            {
                return this.ImgField;
            }
            set
            {
                this.ImgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, System.Collections.Generic.KeyValuePair<string, ModemWebUtility.ModemPostObjects>[]>[] Links
        {
            get
            {
                return this.LinksField;
            }
            set
            {
                this.LinksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchBoxItemClass", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceModemToolbarSync")]
    public partial class SearchBoxItemClass : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ButtonTextField;
        
        private string ButtonTooltipField;
        
        private string ClearHistoryTextField;
        
        private string GreetingTextField;
        
        private System.Drawing.Image ImgField;
        
        private System.Windows.Forms.FlatStyle InputBoxFlatStyleField;
        
        private System.Drawing.Size InputBoxSizeField;
        
        private string SearchBoxTooltipField;
        
        private string SearchURLField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ButtonText
        {
            get
            {
                return this.ButtonTextField;
            }
            set
            {
                this.ButtonTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ButtonTooltip
        {
            get
            {
                return this.ButtonTooltipField;
            }
            set
            {
                this.ButtonTooltipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClearHistoryText
        {
            get
            {
                return this.ClearHistoryTextField;
            }
            set
            {
                this.ClearHistoryTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GreetingText
        {
            get
            {
                return this.GreetingTextField;
            }
            set
            {
                this.GreetingTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Image Img
        {
            get
            {
                return this.ImgField;
            }
            set
            {
                this.ImgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Windows.Forms.FlatStyle InputBoxFlatStyle
        {
            get
            {
                return this.InputBoxFlatStyleField;
            }
            set
            {
                this.InputBoxFlatStyleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Size InputBoxSize
        {
            get
            {
                return this.InputBoxSizeField;
            }
            set
            {
                this.InputBoxSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchBoxTooltip
        {
            get
            {
                return this.SearchBoxTooltipField;
            }
            set
            {
                this.SearchBoxTooltipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchURL
        {
            get
            {
                return this.SearchURLField;
            }
            set
            {
                this.SearchURLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkListItemClass", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceModemToolbarSync")]
    public partial class LinkListItemClass : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CaptionField;
        
        private string HintField;
        
        private System.Drawing.Image ImgField;
        
        private System.Collections.Generic.KeyValuePair<string, string>[] LinksField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption
        {
            get
            {
                return this.CaptionField;
            }
            set
            {
                this.CaptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hint
        {
            get
            {
                return this.HintField;
            }
            set
            {
                this.HintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Image Img
        {
            get
            {
                return this.ImgField;
            }
            set
            {
                this.ImgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] Links
        {
            get
            {
                return this.LinksField;
            }
            set
            {
                this.LinksField = value;
            }
        }
    }
}
namespace System.Drawing
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.SerializableAttribute()]
    public partial class Image : object, System.Runtime.Serialization.ISerializable
    {
        
        private System.Runtime.Serialization.SerializationInfo info;
        
        public Image(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
        {
            this.info = info;
        }
        
        public System.Runtime.Serialization.SerializationInfo SerializationInfo
        {
            get
            {
                return this.info;
            }
            set
            {
                this.info = value;
            }
        }
        
        public void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
        {
            if ((this.SerializationInfo == null))
            {
                return;
            }
            System.Runtime.Serialization.SerializationInfoEnumerator enumerator = this.SerializationInfo.GetEnumerator();
            for (
            ; enumerator.MoveNext(); 
            )
            {
                System.Runtime.Serialization.SerializationEntry entry = enumerator.Current;
                info.AddValue(entry.Name, entry.Value);
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Size", Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial struct Size : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int heightField;
        
        private int widthField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }
    }
}
namespace ModemWebUtility
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModemPostObjects", Namespace="http://schemas.datacontract.org/2004/07/ModemWebUtility")]
    public partial class ModemPostObjects : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ModemWebUtility.MwdBhaPosts MwdBhaPostField;
        
        private System.Collections.Generic.Dictionary<int, ModemWebUtility.MwdCompPosts> MwdCompPostDictField;
        
        private System.Collections.Generic.Dictionary<int, ModemWebUtility.MwdSoftPosts> MwdSoftPostDictField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModemWebUtility.MwdBhaPosts MwdBhaPost
        {
            get
            {
                return this.MwdBhaPostField;
            }
            set
            {
                this.MwdBhaPostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, ModemWebUtility.MwdCompPosts> MwdCompPostDict
        {
            get
            {
                return this.MwdCompPostDictField;
            }
            set
            {
                this.MwdCompPostDictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, ModemWebUtility.MwdSoftPosts> MwdSoftPostDict
        {
            get
            {
                return this.MwdSoftPostDictField;
            }
            set
            {
                this.MwdSoftPostDictField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MwdBhaPosts", Namespace="http://schemas.datacontract.org/2004/07/ModemWebUtility")]
    public partial class MwdBhaPosts : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string P_BHA_DESCField;
        
        private string P_BHA_NUMField;
        
        private string P_EXP_MAX_TEMPField;
        
        private string P_HC_TOOLField;
        
        private string P_L_IMPELLERSIZEField;
        
        private string P_L_ORIFFICESIZEField;
        
        private string P_L_STATORSIZEField;
        
        private string P_MWDDWD_ADD_INFOField;
        
        private string P_POPPET_STANDOFFField;
        
        private string P_PULSER_OILTYPEField;
        
        private string P_RASOURCE_IDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_BHA_DESC
        {
            get
            {
                return this.P_BHA_DESCField;
            }
            set
            {
                this.P_BHA_DESCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_BHA_NUM
        {
            get
            {
                return this.P_BHA_NUMField;
            }
            set
            {
                this.P_BHA_NUMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_EXP_MAX_TEMP
        {
            get
            {
                return this.P_EXP_MAX_TEMPField;
            }
            set
            {
                this.P_EXP_MAX_TEMPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_HC_TOOL
        {
            get
            {
                return this.P_HC_TOOLField;
            }
            set
            {
                this.P_HC_TOOLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_L_IMPELLERSIZE
        {
            get
            {
                return this.P_L_IMPELLERSIZEField;
            }
            set
            {
                this.P_L_IMPELLERSIZEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_L_ORIFFICESIZE
        {
            get
            {
                return this.P_L_ORIFFICESIZEField;
            }
            set
            {
                this.P_L_ORIFFICESIZEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_L_STATORSIZE
        {
            get
            {
                return this.P_L_STATORSIZEField;
            }
            set
            {
                this.P_L_STATORSIZEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_MWDDWD_ADD_INFO
        {
            get
            {
                return this.P_MWDDWD_ADD_INFOField;
            }
            set
            {
                this.P_MWDDWD_ADD_INFOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_POPPET_STANDOFF
        {
            get
            {
                return this.P_POPPET_STANDOFFField;
            }
            set
            {
                this.P_POPPET_STANDOFFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_PULSER_OILTYPE
        {
            get
            {
                return this.P_PULSER_OILTYPEField;
            }
            set
            {
                this.P_PULSER_OILTYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_RASOURCE_ID
        {
            get
            {
                return this.P_RASOURCE_IDField;
            }
            set
            {
                this.P_RASOURCE_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MwdCompPosts", Namespace="http://schemas.datacontract.org/2004/07/ModemWebUtility")]
    public partial class MwdCompPosts : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string P_COMMENTSField;
        
        private string P_DESCRIPTIONField;
        
        private string P_L_THREAD_BTMField;
        
        private string P_L_THREAD_TOPField;
        
        private string P_L_TORQUEField;
        
        private string P_SEQ_NOField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_COMMENTS
        {
            get
            {
                return this.P_COMMENTSField;
            }
            set
            {
                this.P_COMMENTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_DESCRIPTION
        {
            get
            {
                return this.P_DESCRIPTIONField;
            }
            set
            {
                this.P_DESCRIPTIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_L_THREAD_BTM
        {
            get
            {
                return this.P_L_THREAD_BTMField;
            }
            set
            {
                this.P_L_THREAD_BTMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_L_THREAD_TOP
        {
            get
            {
                return this.P_L_THREAD_TOPField;
            }
            set
            {
                this.P_L_THREAD_TOPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_L_TORQUE
        {
            get
            {
                return this.P_L_TORQUEField;
            }
            set
            {
                this.P_L_TORQUEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_SEQ_NO
        {
            get
            {
                return this.P_SEQ_NOField;
            }
            set
            {
                this.P_SEQ_NOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MwdSoftPosts", Namespace="http://schemas.datacontract.org/2004/07/ModemWebUtility")]
    public partial class MwdSoftPosts : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string P_L_MSR_SENSORField;
        
        private string P_OPS_VERSIONField;
        
        private string P_WS_VERSIONField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_L_MSR_SENSOR
        {
            get
            {
                return this.P_L_MSR_SENSORField;
            }
            set
            {
                this.P_L_MSR_SENSORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_OPS_VERSION
        {
            get
            {
                return this.P_OPS_VERSIONField;
            }
            set
            {
                this.P_OPS_VERSIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P_WS_VERSION
        {
            get
            {
                return this.P_WS_VERSIONField;
            }
            set
            {
                this.P_WS_VERSIONField = value;
            }
        }
    }
}
namespace System.Windows.Forms
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatStyle", Namespace="http://schemas.datacontract.org/2004/07/System.Windows.Forms")]
    public enum FlatStyle : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Flat = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Popup = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standard = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 3,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWCFModemService")]
public interface IWCFModemService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetSyncStatus", ReplyAction="http://tempuri.org/IWCFModemService/GetSyncStatusResponse")]
    int GetSyncStatus();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetSyncStatus", ReplyAction="http://tempuri.org/IWCFModemService/GetSyncStatusResponse")]
    System.Threading.Tasks.Task<int> GetSyncStatusAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetDataMenuListItemClass", ReplyAction="http://tempuri.org/IWCFModemService/GetDataMenuListItemClassResponse")]
    WcfServiceModemToolbarSync.MenuListItemClass[] GetDataMenuListItemClass();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetDataMenuListItemClass", ReplyAction="http://tempuri.org/IWCFModemService/GetDataMenuListItemClassResponse")]
    System.Threading.Tasks.Task<WcfServiceModemToolbarSync.MenuListItemClass[]> GetDataMenuListItemClassAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetDataSearchBoxItemClass", ReplyAction="http://tempuri.org/IWCFModemService/GetDataSearchBoxItemClassResponse")]
    WcfServiceModemToolbarSync.SearchBoxItemClass[] GetDataSearchBoxItemClass();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetDataSearchBoxItemClass", ReplyAction="http://tempuri.org/IWCFModemService/GetDataSearchBoxItemClassResponse")]
    System.Threading.Tasks.Task<WcfServiceModemToolbarSync.SearchBoxItemClass[]> GetDataSearchBoxItemClassAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetDataLinkListItemClass", ReplyAction="http://tempuri.org/IWCFModemService/GetDataLinkListItemClassResponse")]
    WcfServiceModemToolbarSync.LinkListItemClass[] GetDataLinkListItemClass();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetDataLinkListItemClass", ReplyAction="http://tempuri.org/IWCFModemService/GetDataLinkListItemClassResponse")]
    System.Threading.Tasks.Task<WcfServiceModemToolbarSync.LinkListItemClass[]> GetDataLinkListItemClassAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWCFModemServiceChannel : IWCFModemService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WCFModemServiceClient : System.ServiceModel.ClientBase<IWCFModemService>, IWCFModemService
{
    
    public WCFModemServiceClient()
    {
    }
    
    public WCFModemServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WCFModemServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFModemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFModemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetSyncStatus()
    {
        return base.Channel.GetSyncStatus();
    }
    
    public System.Threading.Tasks.Task<int> GetSyncStatusAsync()
    {
        return base.Channel.GetSyncStatusAsync();
    }
    
    public WcfServiceModemToolbarSync.MenuListItemClass[] GetDataMenuListItemClass()
    {
        return base.Channel.GetDataMenuListItemClass();
    }
    
    public System.Threading.Tasks.Task<WcfServiceModemToolbarSync.MenuListItemClass[]> GetDataMenuListItemClassAsync()
    {
        return base.Channel.GetDataMenuListItemClassAsync();
    }
    
    public WcfServiceModemToolbarSync.SearchBoxItemClass[] GetDataSearchBoxItemClass()
    {
        return base.Channel.GetDataSearchBoxItemClass();
    }
    
    public System.Threading.Tasks.Task<WcfServiceModemToolbarSync.SearchBoxItemClass[]> GetDataSearchBoxItemClassAsync()
    {
        return base.Channel.GetDataSearchBoxItemClassAsync();
    }
    
    public WcfServiceModemToolbarSync.LinkListItemClass[] GetDataLinkListItemClass()
    {
        return base.Channel.GetDataLinkListItemClass();
    }
    
    public System.Threading.Tasks.Task<WcfServiceModemToolbarSync.LinkListItemClass[]> GetDataLinkListItemClassAsync()
    {
        return base.Channel.GetDataLinkListItemClassAsync();
    }
}
