//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModemToolbarIE.ModemService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModemService.IWCFModemService")]
    public interface IWCFModemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetSyncStatus", ReplyAction="http://tempuri.org/IWCFModemService/GetSyncStatusResponse")]
        int GetSyncStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetSyncStatus", ReplyAction="http://tempuri.org/IWCFModemService/GetSyncStatusResponse")]
        System.Threading.Tasks.Task<int> GetSyncStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetMenuListItemClasses", ReplyAction="http://tempuri.org/IWCFModemService/GetMenuListItemClassesResponse")]
        WcfServiceModemToolbarSync.MenuListClass GetMenuListItemClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetMenuListItemClasses", ReplyAction="http://tempuri.org/IWCFModemService/GetMenuListItemClassesResponse")]
        System.Threading.Tasks.Task<WcfServiceModemToolbarSync.MenuListClass> GetMenuListItemClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetSearchBoxItemClasses", ReplyAction="http://tempuri.org/IWCFModemService/GetSearchBoxItemClassesResponse")]
        WcfServiceModemToolbarSync.SearchListClass GetSearchBoxItemClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetSearchBoxItemClasses", ReplyAction="http://tempuri.org/IWCFModemService/GetSearchBoxItemClassesResponse")]
        System.Threading.Tasks.Task<WcfServiceModemToolbarSync.SearchListClass> GetSearchBoxItemClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetLinkListItemClasses", ReplyAction="http://tempuri.org/IWCFModemService/GetLinkListItemClassesResponse")]
        WcfServiceModemToolbarSync.LinkListClass GetLinkListItemClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFModemService/GetLinkListItemClasses", ReplyAction="http://tempuri.org/IWCFModemService/GetLinkListItemClassesResponse")]
        System.Threading.Tasks.Task<WcfServiceModemToolbarSync.LinkListClass> GetLinkListItemClassesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFModemServiceChannel : ModemToolbarIE.ModemService.IWCFModemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFModemServiceClient : System.ServiceModel.ClientBase<ModemToolbarIE.ModemService.IWCFModemService>, ModemToolbarIE.ModemService.IWCFModemService {
        
        public WCFModemServiceClient() {
        }
        
        public WCFModemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFModemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFModemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFModemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSyncStatus() {
            return base.Channel.GetSyncStatus();
        }
        
        public System.Threading.Tasks.Task<int> GetSyncStatusAsync() {
            return base.Channel.GetSyncStatusAsync();
        }
        
        public WcfServiceModemToolbarSync.MenuListClass GetMenuListItemClasses() {
            return base.Channel.GetMenuListItemClasses();
        }
        
        public System.Threading.Tasks.Task<WcfServiceModemToolbarSync.MenuListClass> GetMenuListItemClassesAsync() {
            return base.Channel.GetMenuListItemClassesAsync();
        }
        
        public WcfServiceModemToolbarSync.SearchListClass GetSearchBoxItemClasses() {
            return base.Channel.GetSearchBoxItemClasses();
        }
        
        public System.Threading.Tasks.Task<WcfServiceModemToolbarSync.SearchListClass> GetSearchBoxItemClassesAsync() {
            return base.Channel.GetSearchBoxItemClassesAsync();
        }
        
        public WcfServiceModemToolbarSync.LinkListClass GetLinkListItemClasses() {
            return base.Channel.GetLinkListItemClasses();
        }
        
        public System.Threading.Tasks.Task<WcfServiceModemToolbarSync.LinkListClass> GetLinkListItemClassesAsync() {
            return base.Channel.GetLinkListItemClassesAsync();
        }
    }
}
